#' Google Sheets API
#' Reads and writes Google Sheets.
#'
#' Auto-generated code by googleAuthR::gar_create_api_skeleton
#'  at 2018-08-28 13:36:10
#' filename: ~/Desktop/delete_me//googlesheetsv4.auto/R/sheets_functions.R
#' api_json: api_json
#'
#' @details
#' Authentication scopes used are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/spreadsheets.readonly
#' \item https://www.googleapis.com/auth/spreadsheets
#' }
#'
#' @docType package
#' @name sheets_googleAuthR
#'
NULL
## NULL

#' A helper function that tests whether an object is either NULL _or_
#' a list of NULLs
#'
#' @keywords internal
is.NullOb <- function(x) is.null(x) | all(sapply(x, is.null))
#' Recursively step down into list, removing all such objects
#'
#' @keywords internal
rmNullObs <- function(x) {
    x <- Filter(Negate(is.NullOb), x)
    lapply(x, function(x) if (is.list(x))
        rmNullObs(x) else x)
}

#' Creates a spreadsheet, returning the newly created spreadsheet.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/sheets/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/spreadsheets
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/spreadsheets)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param Spreadsheet The \link{Spreadsheet} object to pass to this method
#' #' @importFrom googleAuthR gar_api_generator
#' @family Spreadsheet functions
#' @export
spreadcreate <- function(Spreadsheet) {
    url <- "https://sheets.googleapis.com/v4/spreadsheets"
    # sheets.spreadsheets.create
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(Spreadsheet, "gar_Spreadsheet"))

    f(the_body = Spreadsheet)

}

#' Applies one or more updates to the spreadsheet.Each request is validated beforebeing applied. If any request is not valid then the entire request willfail and nothing will be applied.Some requests have replies togive you some information about howthey are applied. The replies will mirror the requests.  For example,if you applied 4 updates and the 3rd one had a reply, then theresponse will have 2 empty replies, the actual reply, and another emptyreply, in that order.Due to the collaborative nature of spreadsheets, it is not guaranteed thatthe spreadsheet will reflect exactly your changes after this completes,however it is guaranteed that the updates in the request will beapplied together atomically. Your changes may be altered with respect tocollaborator changes. If there are no collaborators, the spreadsheetshould reflect your changes.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/sheets/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/spreadsheets
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/spreadsheets)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param BatchUpdateSpreadsheetRequest The \link{BatchUpdateSpreadsheetRequest} object to pass to this method
#' @param spreadsheetId The spreadsheet to apply the updates to
#' @importFrom googleAuthR gar_api_generator
#' @family BatchUpdateSpreadsheetRequest functions
#' @export
spreadbatchUpdate <- function(BatchUpdateSpreadsheetRequest, spreadsheetId) {
    url <- sprintf("https://sheets.googleapis.com/v4/spreadsheets/%s:batchUpdate",
        spreadsheetId)
    # sheets.spreadsheets.batchUpdate
    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)
    stopifnot(inherits(BatchUpdateSpreadsheetRequest, "gar_BatchUpdateSpreadsheetRequest"))

    f(the_body = BatchUpdateSpreadsheetRequest)

}

#' Returns the spreadsheet at the given ID.The caller must specify the spreadsheet ID.By default, data within grids will not be returned.You can include grid data one of two ways:* Specify a field mask listing your desired fields using the `fields` URLparameter in HTTP* Set the includeGridDataURL parameter to true.  If a field mask is set, the `includeGridData`parameter is ignoredFor large spreadsheets, it is recommended to retrieve only the specificfields of the spreadsheet that you want.To retrieve only subsets of the spreadsheet, use theranges URL parameter.Multiple ranges can be specified.  Limiting the range willreturn only the portions of the spreadsheet that intersect the requestedranges. Ranges are specified using A1 notation.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/sheets/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/drive.readonly
#' \item https://www.googleapis.com/auth/spreadsheets
#' \item https://www.googleapis.com/auth/spreadsheets.readonly
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/drive.readonly, https://www.googleapis.com/auth/spreadsheets, https://www.googleapis.com/auth/spreadsheets.readonly)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param spreadsheetId The spreadsheet to request
#' @param ranges The ranges to retrieve from the spreadsheet
#' @param includeGridData True if grid data should be returned
#' @importFrom googleAuthR gar_api_generator
#' @export
spreadget <- function(spreadsheetId, ranges = NULL, includeGridData = NULL) {
    url <- sprintf("https://sheets.googleapis.com/v4/spreadsheets/%s", spreadsheetId)
    # sheets.spreadsheets.get
    pars = list(ranges = ranges, includeGridData = includeGridData)
    f <- googleAuthR::gar_api_generator(url, "GET", pars_args = rmNullObs(pars),
        data_parse_function = function(x) x)
    f()

}


#' Returns the spreadsheet at the given ID.The caller must specify the spreadsheet ID.This method differs from GetSpreadsheet in that it allows selectingwhich subsets of spreadsheet data to return by specifying adataFilters parameter.Multiple DataFilters can be specified.  Specifying one ormore data filters will return the portions of the spreadsheet thatintersect ranges matched by any of the filters.By default, data within grids will not be returned.You can include grid data one of two ways:* Specify a field mask listing your desired fields using the `fields` URLparameter in HTTP* Set the includeGridDataparameter to true.  If a field mask is set, the `includeGridData`parameter is ignoredFor large spreadsheets, it is recommended to retrieve only the specificfields of the spreadsheet that you want.
#'
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_skeleton}}
#'
#' @seealso \href{https://developers.google.com/sheets/}{Google Documentation}
#'
#' @details
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/drive
#' \item https://www.googleapis.com/auth/drive.file
#' \item https://www.googleapis.com/auth/spreadsheets
#' }
#'
#' Set \code{options(googleAuthR.scopes.selected = c(https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/drive.file, https://www.googleapis.com/auth/spreadsheets)}
#' Then run \code{googleAuthR::gar_auth()} to authenticate.
#' See \code{\link[googleAuthR]{gar_auth}} for details.
#'
#' @param GetSpreadsheetByDataFilterRequest The \link{GetSpreadsheetByDataFilterRequest} object to pass to this method
#' @param spreadsheetId The spreadsheet to request
#' @importFrom googleAuthR gar_api_generator
#' @family GetSpreadsheetByDataFilterRequest functions
#' @export
spreadgetByDataFilter <- function(GetSpreadsheetByDataFilterRequest, spreadsheetId) {


    url <- sprintf("https://sheets.googleapis.com/v4/spreadsheets/%s:getByDataFilter",
        spreadsheetId)
    # sheets.spreadsheets.getByDataFilter

    f <- googleAuthR::gar_api_generator(url, "POST", data_parse_function = function(x) x)

    stopifnot(inherits(GetSpreadsheetByDataFilterRequest, "gar_GetSpreadsheetByDataFilterRequest"))

    f(the_body = GetSpreadsheetByDataFilterRequest)


}


#' Execute Google Sheets Method `spreadsheets.values.update`
#'
#' [v4 API Doc](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/update)
#'
#' @param spreadsheet_id atomic character vector length 1; The ID of the
#'   spreadsheet to update.
#' @param value_input_option atomic character length 1; How the input data
#'   should be interpreted.
#' @param include_values_in_response atomic logical length 1; Determines if the
#'   update response should include the values of the cells that were updated.
#'   By default, responses do not include the updated values. If the range to
#'   write was larger than than the range actually written, the response will
#'   include all values in the requested range (excluding trailing empty rows
#'   and columns).
#' @param response_value_render_option atomic character length 1; Determines
#'   how values in the response should be rendered. The default render option
#'   is ValueRenderOption.FORMATTED_VALUE.
#' @param response_date_time_render_option atomic character length 1; Determines
#'   how dates, times, and durations in the response should be rendered. This
#'   is ignored if responseValueRenderOption is FORMATTED_VALUE. The default
#'   dateTime render option is [DateTimeRenderOption.SERIAL_NUMBER].
#' @param value_range ValueRange object; to be passed to value request body
#' @param simplify_vector passed to jsonlite::fromJSON, defaults to FALSE
#'
#' @return update_values_response object (list)
#' @export
gsheet_update_ss_values <- function(spreadsheet_id,
                                    value_range,
                                    value_input_option = "USER_ENTERED",
                                    include_values_in_response = FALSE,
                                    response_value_render_option = "FORMATTED_VALUE",
                                    response_date_time_render_option = "SERIAL_NUMBER",
                                    simplify_vector = FALSE) {

  stopifnot(inherits(value_range, "gar_ValueRange"))
  range <- value_range[["range"]]

  f <- googleAuthR::gar_api_generator(
    baseURI = "https://sheets.googleapis.com/v4/",
    http_header = 'PUT',
    path_args = list(spreadsheets = spreadsheet_id,
                     values = range),
    pars_args = list(valueInputOption = value_input_option,
                     includeValuesInResponse = include_values_in_response,
                     responseValueRenderOption = response_value_render_option,
                     responseDateTimeRenderOption = response_date_time_render_option),
    simplifyVector = simplify_vector
  )

  f(the_body = value_range)
}


#' Execute Google Sheets `spreadsheets.values.clear method`
#'
#' [v4 API Doc](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get)
#'
#' @param spreadsheet_id The ID of the spreadsheet to retrieve data from.
#' @param range The A1 notation of the values to clear
#' @param simplify_vector passed to jsonlite::fromJSON, defaults to FALSE
#'
#' @return list with spreadsheetId and clearedRange
#' @export
gsheet_clear_ss_values <- function(spreadsheet_id,
                                   range,
                                   simplify_vector = FALSE) {

  args <- list()
  args[[spreadsheet_id]] <- "values"
  args[[range]] <- ":clear"

  f <- googleAuthR::gar_api_generator(
    baseURI = "https://sheets.googleapis.com/v4/spreadsheets/",
    http_header = 'POST',
    path_args = args,
    simplifyVector = simplify_vector
  )

  f()
}
